/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qt4java_QMainWindow */

#ifndef _Included_qt4java_QMainWindow
#define _Included_qt4java_QMainWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qt4java_QMainWindow
 * Method:    create
 * Signature: (Lqt4java/QObject;I)J
 */
JNIEXPORT jlong JNICALL Java_qt4java_QMainWindow_create
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
