/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qt4java_QObject */

#ifndef _Included_qt4java_QObject
#define _Included_qt4java_QObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qt4java_QObject
 * Method:    create
 * Signature: (Lqt4java/QObject;)J
 */
JNIEXPORT jlong JNICALL Java_qt4java_QObject_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     qt4java_QObject
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_qt4java_QObject_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
