/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qt4java_QWidget */

#ifndef _Included_qt4java_QWidget
#define _Included_qt4java_QWidget
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qt4java_QWidget
 * Method:    create
 * Signature: (Lqt4java/QWidget;I)J
 */
JNIEXPORT jlong JNICALL Java_qt4java_QWidget_create
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     qt4java_QWidget
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_qt4java_QWidget_show
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
