/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qt4java_QPushButton */

#ifndef _Included_qt4java_QPushButton
#define _Included_qt4java_QPushButton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qt4java_QPushButton
 * Method:    create
 * Signature: (Ljava/lang/String;Lqt4java/QWidget;)J
 */
JNIEXPORT jlong JNICALL Java_qt4java_QPushButton_create
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
