/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qt4java_QApplication */

#ifndef _Included_qt4java_QApplication
#define _Included_qt4java_QApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qt4java_QApplication
 * Method:    exec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_qt4java_QApplication_exec
  (JNIEnv *, jobject);

/*
 * Class:     qt4java_QApplication
 * Method:    create
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_qt4java_QApplication_create
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
